name: Maven Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  deploy:
    needs: build
    runs-on: [ubuntu-latest]
    name: Deploy Event
    steps:
    - name: Webhook Action
      uses: joelwmale/webhook-action@1.0.0
      env:
        WEBHOOK_URL: https://www.lordgasmic.com
        data: "{'deployment': 'finished', 'project': 'actions'}"

    
